<?php

namespace SupplierBundle\Repository;

/**
 * EastendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EastendRepository extends \Doctrine\ORM\EntityRepository
{
}
