<?php

namespace SupplierBundle\Repository;

/**
 * JsonRawRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JsonRawRepository extends \Doctrine\ORM\EntityRepository
{
}
