<?php

namespace StockBundle\Repository;

/**
 * StockLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockLineRepository extends \Doctrine\ORM\EntityRepository
{
}
