<?php

namespace FeedBundle\Repository;

/**
 * EanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EanRepository extends \Doctrine\ORM\EntityRepository
{
}
