stock:
    resource: "@StockBundle/Controller/"
    type:     annotation
    prefix:   /

feed:
    resource: "@FeedBundle/Controller/"
    type:     annotation
    prefix:   /

supplier:
    resource: "@SupplierBundle/Controller/"
    type:     annotation
    prefix:   /

product:
    resource: "@ProductBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin